---
title: "16S multifasta generation"
author: "Aadi Pallerla"
date: "2024-02-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(seqinr)
library(BiocGenerics)
library(Biostrings)
```

```{r}

taxa <- readRDS("../data/2023-07-26_16S-taxa.rds") %>%
  as.data.frame() %>%
  filter(Family == "Lachnospiraceae") %>%
  rownames_to_column(var = "ASV") %>%
  select(-Kingdom,-Phylum,-Class,-Order) %>%
  rownames_to_column(var = "ID") 

taxa.spec <- taxa %>%
  filter(!is.na(Species)) %>%
  mutate(ASVID = paste0("ASV",ID),
         Fasta = paste(Genus,Species,ASVID,sep = " ")) %>%
  select(ID,ASV,Fasta)


taxa.fill <- taxa %>%
  filter(is.na(Species)) %>%
  mutate(Genus=if_else(is.na(Genus),paste0("g_unclassified_",Family),Genus),
         Species=if_else(is.na(Species),paste0("s_unclassified_",Genus),Species),
         Species=str_replace(Species,"s_unclassified_g_unclassified_","s_g_unclassified_")) %>%
  mutate(ASVID = paste0("ASV",ID),
         Fasta = paste(Species,ASVID,sep = " ")) %>%
  select(ID,ASV,Fasta)

taxa.combine <- bind_rows(taxa.fill,
                          taxa.spec) %>%
  mutate(ID = as.numeric(ID)) %>%
  arrange(ID)

ASVs <- as.vector(taxa.combine$ASV)
ID.Name <- as.vector(taxa.combine$Fasta)

names(ASVs) <- ID.Name

string <- AAStringSet(ASVs)

writeXStringSet(string,"../data/BEWELL_Lachno-ASV.mfa")
```

    
