---
title: "Combined Mimic Boxplot"
author: "Aadi Pallerla"
date: '2022-06-30'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(tidyverse)
source("00-paths.R")
```

```{r}
processed.data <- read.csv("../data/2022-08-11_tumor-size_R-formatted.csv") %>%
  mutate(treatment = fct_relevel(treatment, "IgG")) %>%
  mutate(treatment.group = paste(treatment, microbiome.sample, sep = " x ")) %>%
  mutate(treatment = as.character(treatment))
```

```{r final processed output}

max.final.processed <-
  processed.data %>%
  group_by(experiment) %>%
  summarise(max(days.from.injection)) %>%
  rename("days.from.injection" = "max(days.from.injection)")

#mimic 2,4 have a couple different final days, need to add those in
mim2.add <-
  processed.data %>%
  filter(experiment == "mimic2") %>%
  filter(days.from.injection == 20)
mim4.add <-
  processed.data %>%
  filter(experiment == "mimic4") %>%
  filter(days.from.injection == 19)

final.processed <- 
  semi_join(processed.data, 
            max.final.processed,
            by = "days.from.injection") %>%
  bind_rows(mim2.add, mim4.add) %>%
  mutate(experiment = as.factor(experiment)) %>%
  mutate(experiment = fct_relevel(experiment, "mimic10","mimic11","mimic12", "mimic13", after = 9)) %>%
  mutate(treatment = if_else(grepl("PD1", treatment),
                             true = "Anti-PD1",
                             false = treatment)) %>%
  mutate(gavage = if_else(grepl("v1|v3", microbiome.sample),
                          true = "Pre-BRB",
                          false = if_else(grepl("v2|v4", microbiome.sample),
                                          true = "Post-BRB",
                                          false = "other"))) %>%
  mutate(gavage = fct_relevel(gavage, "Pre-BRB"))
```

```{r final boxplot}
final.processed %>%
  ggplot(aes(x = treatment.group, y = tumor.volume)) +
  geom_boxplot(fill = '#872657') +
  facet_wrap(. ~ experiment, nrow = 3, scales = "free") +
  theme_bw() +
  ggtitle("Mimic Tumor Measurements for Final Timepoint") + 
  theme(axis.text.x = element_text(size = 5.5, angle = 45, hjust = .9)) +
  xlab("Treatment Group") +
  ylab("Tumor Volume")

ggsave("../figures/mimic-combined-boxplot.png", width = 10, height = 8)
```

```{r mimic bewell filtered final output}

H55.filter <-
  final.processed %>%
  filter(experiment %in% c("mimic1","mimic6","mimic7")) %>%
  mutate(patient = "HONC60-55: Random Sample")
H102.filter <-
  final.processed %>%
  filter(experiment == "mimic5") %>%
  mutate(patient = "HONC60-102")
H68.filter <-
  final.processed %>%
  filter(experiment == "mimic10") %>%
  mutate(patient = "HONC60-68: Roseburia + Blautia")
H79.filter <-
  final.processed %>%
  filter(experiment == "mimic11") %>%
  mutate(patient = "HONC60-79: Lachnospira",
         gavage = if_else(grepl("v2", microbiome.sample),
                          true = "Post-Placebo",
                          false = "Post-BRB"))
H85.filter <-
  final.processed %>%
  filter(experiment == "mimic12") %>%
  mutate(patient = "HONC60-85: Blautia") 
H84.filter <-
  final.processed %>%
  filter(experiment == "mimic13") %>%
  mutate(patient = "HONC60-84: Blautia") 

bewell.filter <-
  bind_rows(H55.filter,
            H102.filter,
            H68.filter,
            H79.filter,
            H85.filter,
            H84.filter) %>%
  mutate(treatment = fct_relevel(treatment, "IgG")) %>%
   mutate(gavage = fct_relevel(gavage, "Pre-BRB", "Post-Placebo"))

```

```{r bewell separate boxplot}

bewell.filter %>%
  ggplot(aes(x = treatment, y = tumor.volume, fill = gavage)) +
  geom_boxplot() +
  facet_wrap(. ~ patient, scales = "free_y") +
  xlab("Treatment") +
  ylab("Tumor Volume") +
  ggtitle("Mimic Bewell Samples Final Tumor Volume") +
  theme_bw()

ggsave("../figures/BEWELL-filtered-boxplot.png", width = 10, height = 8)

```


```{r}

df <- 
  final.processed %>%
  mutate(patient = if_else(experiment %in% c("mimic1","mimic6","mimic7"),
                           true = "55",
                           false = if_else(experiment %in% c("mimic5"),
                                           true = "10",
                                           false = if_else(experiment %in% c("mimic10"),
                                                           true = "68",
                                                           false = "other")
                                           )))

df %>%
  group_by(patient) %>%
  tally
```

```{r}
df %>%
  filter(patient != "other") %>%
  filter(treatment == "Anti-PD1") %>%
  ggplot(aes(x = patient, y = tumor.volume)) +
  geom_boxplot(aes(fill = gavage)) +
  theme_bw(base_size = 18) +
  scale_fill_brewer(palette = "Set1") +
  labs(x = "Participant Sample",
       y = "Tumor Volume (mm^3)",
       fill = "Gavage")
  # geom_jitter(aes(color = gavage), width = 0.9)

ggsave("../figures/ACC22_bewell-samples_PD1-only_boxplot.png",
       height = 5, width = 5)
```

```{r}
test.68 <- 
  df %>%
  filter(patient == "68") %>%
  pivot_wider(values_from = tumor.volume, names_from = gavage)


t.test(test.68$`Pre-BRB`, test.68$`Post-BRB`)
wilcox.test(test.68$`Pre-BRB`, test.68$`Post-BRB`)
```

















