---
title: "Blautia boxplots"
author: "Rebecca Hoyd"
date: "10/11/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggtext)
```

# Load data

```{r}
mics <- read.csv("/fs/ess/PAS1695/projects/recrad/data/mouseexp_2023/counts_exotic.csv")
```

# Find samples

```{r}
samps <- unique(mics$sample)
samps <- samps[grepl("_m", samps)]
samps

# Found by searching mimic sample inventory google sheet
Blautia.stat <- c("Yes", "No", "Yes", "Yes", "No", "No")

labdf <- as.data.frame(cbind(sample = samps, blautia = Blautia.stat))
```

# RAs for plot

```{r}
RAs <- mics %>%
  mutate(totcount = sum(exo.ra), .by = sample) %>%
  mutate(ra = exo.ra/totcount) %>%
  group_by(sample, genus) %>%
  summarize(ra = sum(ra)) %>%
  inner_join(labdf) %>%
  filter(genus == "g__Blautia")

save(RAs, file = "../data/plotdat_boxplots_ACS2023.rda")
```

# Plot

```{r}
load("../data/plotdat_boxplots_ACS2023.rda")
RAs %>%
  ggplot(aes(x = blautia, y = ra)) +
  geom_boxplot() +
  geom_point() +
  labs(x = "<i>Blautia</i> gavaged", y = "<i>Blautia</i> relative abundance") +
  theme_bw() +
  theme(text = element_text(size = 9),
        axis.title.x = element_markdown(),
        axis.title.y = element_markdown())
ggsave("../figures/ACS23_boxplot_blautia.png", height = 2, width = 2)
```

