---
title: "mimic11_flowanalysis"
author: "Yangyang Liu"
date: "7/26/2022"
output: html_document
---
#Adapted from Dan Spakowicz

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

```{r data}

x <- read_csv("../data/flow-cytometry/Jul-18-22-mimic11_flow_manedited.csv") %>%
  rename("mouse.cage" = "...1") %>%
  filter(grepl("^M", mouse.cage)) %>%
  mutate(BRB = fct_relevel(BRB, "pre")) %>%
  rename("Gavage" = "BRB") %>%
  mutate(Gavage = if_else(grepl("pre", Gavage),
                          true = "Post-Placebo",
                          false = "Post-BRB"))
  

head(x)
```

```{r}
xl <- 
  x %>%
  gather(-mouse.cage, -Gavage, -Treatment, key = "Marker", value = "Percent") %>%
  mutate(Gavage = fct_relevel(Gavage, c("Post-Placebo"))) %>%
  mutate(Treatment = fct_relevel(Treatment, c("IgG")))

head(xl)
```
```{r separate by CD45 or CD3 marker}
#Setting up CD45 based dataframe
CD45<- subset(xl, Marker=="CD45",
select=mouse.cage:Percent)
CD45_CD4<-subset(xl, Marker=="CD45_CD4",
select=mouse.cage:Percent) 
CD45_CD8<-subset(xl, Marker=="CD45_CD8",
select=mouse.cage:Percent) 

CD45base <- data.frame(rbind(CD45, CD45_CD4, CD45_CD8))
CD45base$Percent = as.numeric(gsub("[\\%,]", "", CD45base$Percent))

#Setting up CD3 based dataframe
CD3<- subset(xl, Marker=="CD3",
select=mouse.cage:Percent)
CD3_CD4<-subset(xl, Marker=="CD3_CD4",
select=mouse.cage:Percent) 
CD3_CD8<-subset(xl, Marker=="CD3_CD8",
select=mouse.cage:Percent) 

CD3base <- data.frame(rbind(CD3, CD3_CD4, CD3_CD8))
CD3base$Percent = as.numeric(gsub("[\\%,]", "", CD3base$Percent))

```


```{r Flwo cell percentages plot}
CD45base %>%
  ggplot(aes(x = Treatment, y = Percent)) +
  geom_boxplot(aes(fill = Gavage)) +
  facet_wrap(~Marker) +
  theme_bw(base_size = 10) +
  theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1)) +
  scale_fill_brewer(palette = "Set2")
ggsave("../figures/mimic11_CD45based_flow_boxplot.png",
       height = 5, width = 8)

CD3base %>%
  ggplot(aes(x = Treatment, y = Percent)) +
  geom_boxplot(aes(fill = Gavage)) +
  facet_wrap(~Marker) +
  theme_bw(base_size = 10) +
  theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1)) +
  scale_fill_brewer(palette = "Set2")
ggsave("../figures/mimic11_CD3based_flow_boxplot.png",
       height = 5, width = 8)
```
