---
title: "Mimic23 Tumor Volume and Survival"
author: "Dan Spakowicz"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
library(survminer)
library(survival)
library(ggsurvfit)

# Set paths to locate OneDrive shared mimic folder
source("00-paths.R")
```

```{r}
x <- readxl::read_xlsx("../data/tumor-size/AOT00055028-mimic23/mimic23_tumor-size.xlsx")

head(x)

```

```{r}
y <- 
  x %>%
  drop_na(microbiome.sample) %>%
  filter(!grepl("na|n/a", `tumor.width.(mm)`)) %>%
  mutate(tumor.length.mm = as.numeric(`tumor.length.(mm)`),
         tumor.width.mm = as.numeric(`tumor.width.(mm)`),
         tumor.volume = (tumor.length.mm * (tumor.width.mm^2)) / 2) %>%
  mutate(cage = as.factor(cage)) %>%
  mutate(mouse = paste(tail.number, cage, sep = ".")) %>%
  group_by(mouse, date, microbiome.sample) %>%
  summarize(total.tumor.volume = sum(tumor.volume))
  

head(y)  
```


```{r, warning=FALSE}
y %>%
  ggplot(aes(x = date, y = total.tumor.volume)) +
  geom_line(aes(group = mouse,
                color = microbiome.sample)) +
  theme_bw() +
  facet_wrap(~microbiome.sample)

```
```{r}
y %>%
  ggplot(aes(x = date, y = total.tumor.volume)) +
  geom_smooth(aes(color = microbiome.sample)) +
  theme_bw() +
  facet_wrap(~microbiome.sample)

```
```{r}
y %>%
  ggplot(aes(x = date, y = total.tumor.volume)) +
  geom_smooth(aes(color = microbiome.sample)) +
  theme_bw() 
ggsave("../figures/mimic23.png", 
       height = 3, width =5)
```


```{r}
surv.in <- 
  x %>%
  mutate(mouse = paste(tail.number, cage, sep = ".")) %>%
  # this should work but also removes NA... 
  # == "n/a" only selects those 6 though
  # max days on trial should be 24 
  filter(`tumor.length.(mm)` != "n/a") %>%
    group_by(mouse) %>%
  mutate(tumor.length = as.numeric(`tumor.length.(mm)`),
         tumor.width = as.numeric(`tumor.width.(mm)`)) %>%
  mutate(days.on.trial = max(date) - min(date)) %>%
  ungroup() %>%
  filter(!is.na(microbiome.sample)) %>%
  select(mouse, days.on.trial, microbiome.sample, tumor.length) %>%
  distinct() %>%
  mutate(status = ifelse(days.on.trial < max(days.on.trial), 1, 0)) %>%
  mutate(status = if_else(tumor.length > 16,
                          true = 1,
                          false = status))

head(surv.in)
```

```{r}
surv.m <- ggsurvfit::survfit2(Surv(days.on.trial, status) ~ microbiome.sample, 
                      data = surv.in)

surv.m %>%
  ggsurvfit() +
  add_pvalue()

ggsave("../figures/mimic23_survival.png",
       height = 4, width = 6)
```



