---
title: "Mimic24 Tumor Volume and Survival"
author: "Dan Spakowicz"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
library(survminer)
library(survival)
library(ggsurvfit)

# Set paths to locate OneDrive shared mimic folder
source("00-paths.R")
```

Read in the data.

```{r}
 x <- readxl::read_xlsx("../data/tumor-size/AOT00055226-mimic24/mimic24_tumor-size.xlsx")
# x <- readxl::read_xlsx(file.path(paths$onedrive, 
#                                  "data", 
#                                  "AOT00055226-mimic24", 
#                                  "mimic24_tumor-size.xlsx"))

head(x)
```

```{r}
y <- 
  x %>%
  drop_na(microbiome.sample) %>%
  mutate(tumor.volume = (`tumor.length.(mm)` * (`tumor.width.(mm)`^2)) / 2) %>%
  mutate(mouse = paste(tail.number, cage, sep = "."))

head(y)  
```

```{r, warning=FALSE}
y %>%
  ggplot(aes(x = date, y = tumor.volume)) +
  geom_line(aes(group = mouse,
                color = microbiome.sample)) +
  theme_bw() +
  facet_wrap(~microbiome.sample)

```

```{r}
y %>%
  ggplot(aes(x = date, y = tumor.volume)) +
  geom_smooth(aes(color = microbiome.sample)) +
  theme_bw() +
  facet_wrap(~microbiome.sample)

```

```{r}

y %>%
  ggplot(aes(x = date, y = tumor.volume)) +
  geom_smooth(aes(color = microbiome.sample)) +
  theme_bw() 
ggsave("../figures/Fig4A-mimic24.png", 
       height = 3, width =5)
ggsave("../figures/Fig4A-mimic24.svg", 
       height = 3, width =5)
```
```{r}
y %>%
  mutate(microbiome.sample = factor(microbiome.sample, 
                                    levels = c("PBS", "Agathobacter rectalis", "Blautia obeum", "Blautia massiliensis")),
         microbiome.sample = recode(microbiome.sample, 
                                    "Agathobacter rectalis" = "A. rectalis",
                                    "Blautia obeum" = "B. obeum",
                                    "Blautia massiliensis" = "B. massiliensis")) %>%
  ggplot(aes(x = date, y = tumor.volume)) +
  geom_smooth(aes(color = microbiome.sample)) +
  theme_bw() +
  scale_color_brewer(palette = "Paired", direction = -1) +
  labs(x = "Date", 
       y = "Tumor Volume")


```

```{r}
start_date <- min(y$date, na.rm = TRUE)

y_modified <- y %>%
  filter(microbiome.sample != "PBS") %>%  # Filter out PBS
  mutate(
    microbiome.sample = factor(microbiome.sample, 
                               levels = c("Agathobacter rectalis", "Blautia obeum", "Blautia massiliensis")),
    microbiome.sample = recode(microbiome.sample, 
                               "Agathobacter rectalis" = "A. rectalis",
                               "Blautia obeum" = "B. obeum",
                               "Blautia massiliensis" = "B. massiliensis"),
    days_from_injection = as.numeric(difftime(date, start_date, units = "days"))  # Calculate days from start
  )

# Calculate the maximum days_from_injection value for x-axis scaling
max_days <- max(y_modified$days_from_injection, na.rm = TRUE)

ggplot(y_modified, aes(x = days_from_injection, y = tumor.volume)) +
  geom_smooth(aes(color = microbiome.sample)) +
  theme_bw() +
  scale_color_brewer(palette = "Paired", direction = -1) +
  labs(x = "Days from Tumor Injection",  
       y = "Mean Tumor Volume (mm³)") +
  scale_x_continuous(breaks = seq(0, max_days, by = 5))  # Customize x-axis breaks
ggsave("../figures/Fig4A-mimic24.svg", 
       height = 3, width =5)

```
```{r}
# Filter and modify data
y_modified <- y %>%
  filter(microbiome.sample != "PBS") %>%
  mutate(
    microbiome.sample = factor(microbiome.sample, 
                               levels = c("Agathobacter rectalis", "Blautia obeum", "Blautia massiliensis")),
    microbiome.sample = recode(microbiome.sample, 
                               "Agathobacter rectalis" = "A. rectalis",
                               "Blautia obeum" = "B. obeum",
                               "Blautia massiliensis" = "B. massiliensis"),
    days_from_injection = as.numeric(difftime(date, start_date, units = "days"))
  )

# Calculate the maximum days_from_injection value for x-axis scaling
max_days <- max(y_modified$days_from_injection, na.rm = TRUE)

# Calculate p-values for the groups (example with t-test for illustration)
p_value1 <- t.test(y_modified$tumor.volume[y_modified$microbiome.sample == "A. rectalis"],
                   y_modified$tumor.volume[y_modified$microbiome.sample == "B. obeum"])$p.value
p_value2 <- t.test(y_modified$tumor.volume[y_modified$microbiome.sample == "A. rectalis"],
                   y_modified$tumor.volume[y_modified$microbiome.sample == "B. massiliensis"])$p.value
p_value3 <- t.test(y_modified$tumor.volume[y_modified$microbiome.sample == "B. obeum"],
                   y_modified$tumor.volume[y_modified$microbiome.sample == "B. massiliensis"])$p.value

# Plot with manual annotations
ggplot(y_modified, aes(x = days_from_injection, y = tumor.volume, color = microbiome.sample)) +
  geom_smooth() +
  theme_bw() +
  scale_color_brewer(palette = "Paired", direction = -1) +
  labs(x = "Days from Tumor Injection",  
       y = "Mean Tumor Volume (mm³)") +
  scale_x_continuous(breaks = seq(0, max_days, by = 5))
ggsave("../figures/Fig4A-mimic24.svg", 
       height = 3, width =5)

```

```{r}
y_modified <- y %>%
  filter(microbiome.sample != "PBS") %>%
  mutate(
    microbiome.sample = factor(microbiome.sample, levels = c("Agathobacter rectalis", "Blautia obeum", "Blautia massiliensis")),
    microbiome.sample = recode(microbiome.sample, "Agathobacter rectalis" = "A. rectalis", "Blautia obeum" = "B. obeum", "Blautia massiliensis" = "B. massiliensis"),
    days_from_injection = as.numeric(difftime(date, start_date, units = "days"))
  )

# Calculate p-values and define labels
p_values <- list(
  paste("p =", round(t.test(y_modified$tumor.volume[y_modified$microbiome.sample == "A. rectalis"], y_modified$tumor.volume[y_modified$microbiome.sample == "B. obeum"])$p.value, 3)),
  paste("p =", round(t.test(y_modified$tumor.volume[y_modified$microbiome.sample == "A. rectalis"], y_modified$tumor.volume[y_modified$microbiome.sample == "B. massiliensis"])$p.value, 3)),
  paste("p =", round(t.test(y_modified$tumor.volume[y_modified$microbiome.sample == "B. obeum"], y_modified$tumor.volume[y_modified$microbiome.sample == "B. massiliensis"])$p.value, 3))
)

# Define x position for brackets and y positions based on mean tumor volume
bracket_x <- max(y_modified$days_from_injection, na.rm = TRUE) + 0.5
y_positions <- y_modified %>%
  filter(days_from_injection == max(days_from_injection, na.rm = TRUE)) %>%
  group_by(microbiome.sample) %>%
  summarize(mean_volume = mean(tumor.volume, na.rm = TRUE)) %>%
  arrange(desc(mean_volume)) %>%
  pull(mean_volume)

# Plot with vertical brackets and rotated p-values
ggplot(y_modified, aes(x = days_from_injection, y = tumor.volume, color = microbiome.sample)) +
  geom_smooth() +
  theme_bw() +
  scale_color_brewer(palette = "Paired", direction = -1) +
  labs(x = "Days from Tumor Injection", y = "Mean Tumor Volume (mm³)") +
  
  # Adding bracket-style annotations
  annotate("segment", x = bracket_x, xend = bracket_x, y = y_positions[2], yend = y_positions[1]) +
  annotate("segment", x = bracket_x - 0.3, xend = bracket_x, y = y_positions[2], yend = y_positions[2]) +
  annotate("segment", x = bracket_x - 0.3, xend = bracket_x, y = y_positions[1], yend = y_positions[1]) +
  annotate("text", x = bracket_x + 0.6, y = mean(c(y_positions[1], y_positions[2])), label = p_values[[1]], angle = 270) +

  annotate("segment", x = bracket_x + 1, xend = bracket_x + 1, y = y_positions[3], yend = y_positions[2]) +
  annotate("segment", x = bracket_x + 0.7, xend = bracket_x + 1, y = y_positions[3], yend = y_positions[3]) +
  annotate("segment", x = bracket_x + 0.7, xend = bracket_x + 1, y = y_positions[2], yend = y_positions[2]) +
  annotate("text", x = bracket_x + 1.6, y = mean(c(y_positions[2], y_positions[3])), label = p_values[[3]], angle = 270) +

  annotate("segment", x = bracket_x + 2, xend = bracket_x + 2, y = y_positions[3], yend = y_positions[1]) +
  annotate("segment", x = bracket_x + 1.7, xend = bracket_x + 2, y = y_positions[3], yend = y_positions[3]) +
  annotate("segment", x = bracket_x + 1.7, xend = bracket_x + 2, y = y_positions[1], yend = y_positions[1]) +
  annotate("text", x = bracket_x + 2.6, y = mean(c(y_positions[1], y_positions[3])), label = p_values[[2]], angle = 270)

ggsave("../figures/Fig4A-mimic24.svg", 
       height = 5, width =8)


```
# Longitudinal modeling

Check the distribution of the response variable

```{r}
y %>%
  ggplot(aes(x = tumor.volume)) +
  geom_histogram()

y %>%
  ggplot(aes(x = log(tumor.volume))) +
  geom_histogram()
```


A log transformation looks good.

Now I'll create the time variables

```{r}
z <- 
  y %>%
  mutate(microbe = fct_relevel(microbiome.sample, "PBS")) %>%
  mutate(log.tumor.volume = log(tumor.volume+1)) %>%
  mutate(days = as.Date(date) - as.Date("2024-03-14", "%F")) %>%
  mutate(days = as.numeric(days)) %>%
  mutate(days2 = days^2)
```

```{r}
m1 <- lm(log.tumor.volume ~ days + days2 * microbe,
         data = z)

summary(m1)
```

```{r}
surv.in <- 
  x %>%
  mutate(mouse = paste(tail.number, cage, sep = ".")) %>%
  # this should work but also removes NA... 
  # == "n/a" only selects those 6 though
  # max days on trial should be 24 
  filter(`tumor.length.(mm)` != "n/a") %>%
    group_by(mouse) %>%
  mutate(tumor.length = as.numeric(`tumor.length.(mm)`),
         tumor.width = as.numeric(`tumor.width.(mm)`)) %>%
  mutate(days.on.trial = max(date) - min(date)) %>%
  ungroup() %>%
  filter(!is.na(microbiome.sample)) %>%
  select(mouse, days.on.trial, microbiome.sample, tumor.length) %>%
  distinct() %>%
  mutate(status = ifelse(days.on.trial < max(days.on.trial), 1, 0)) %>%
  mutate(status = if_else(tumor.length > 16,
                          true = 1,
                          false = status))

head(surv.in)
```

```{r}
surv.m <- ggsurvfit::survfit2(Surv(days.on.trial, status) ~ microbiome.sample, 
                      data = surv.in)

surv.m %>%
  ggsurvfit() +
  add_pvalue()

ggsave("../figures/mimic24_survival.png",
       height = 4, width = 6)
```
