---
title: "Mimic.tumor.vs.time"
author: "Yangyang Liu"
date: "6/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load required packages
library(readxl)
library(tidyverse)

# Load file paths
source("00-paths.R")
```

# 1. Read in data 

```{r import data}
raw.tumor.exp1 <- read_xlsx(file.path(paths$box, "data", "AOT00041318-mimic01",
                                 "AOT00041318_size-measurements.xlsx")) %>%
  mutate(expid = 1) 

tumor.cols <- colnames(raw.tumor.exp1)[grep("tumor", colnames(raw.tumor.exp1))]
raw.tumor.exp2 <- read_xlsx(file.path(paths$box, "data", "AOT00042281-mimic02",
                                 "AOT00042281_size_measurements.xlsx")) %>%
  mutate(expid = 2) %>%
  mutate_at(tumor.cols, as.numeric)

raw.tumor.exp3 <- read_xlsx(file.path(paths$box, "data", "AOT00043109-mimic03",
                                 "AOT00043109_size-measurements.xlsx")) %>%
  mutate(expid = 3)
 
raw.tumor.exp1 <- raw.tumor.exp1  %>%
  mutate_at(tumor.cols, as.numeric)
```

```{r}
# I'm pretty sure this is the version that Alvin used? 
raw.tumor <- bind_rows(raw.tumor.exp1, raw.tumor.exp2)

head(raw.tumor)
```

# 2. Clean, format and create variables

```{r}
format_rawtumor <- function(rawtumor){
  # Calculate tumor volume and create other variables needed for plotting
  meas <- 
    rawtumor %>%
    mutate(tumor.volume = (`tumor.length.(mm)` * (`tumor.width.(mm)`^2)) / 2) %>%
    # NA tumor volume means it was too small to be measured -- set to 0
    mutate(tumor.volume = dplyr::if_else(is.na(tumor.volume),
                                         true = 0,
                                         false = tumor.volume)) %>%
    # Adjust the microbiome sample name to generalize
    mutate(condition = dplyr::if_else(grepl("v3", microbiome.sample),
                                      true = "pre-DI",
                                      false = microbiome.sample))%>%
    mutate(condition = dplyr::if_else(grepl("v4", microbiome.sample),
                                      true = "post-DI",
                                      false = microbiome.sample))%>%
    # Create a unique mouse ID
    mutate(mouse = paste(tail.number, treatment, condition, sep = ".")) %>%
    # Create 4 treatment groups
    mutate(treatment.group = paste(condition, treatment, sep = ".")) %>%
    #mutate(treatment.group = fct_relevel(treatment.group,
    #c("pre-DI.IgG",
    #"pre-DI.Anti-PD-1",
    #"post-DI.IgG",
    #"post-DI.Anti-PD-1"))) %>%
    group_by(mouse, date) %>%
    mutate(total.tumor.volume = sum(tumor.volume)) %>%
    distinct(date, mouse, treatment.group, total.tumor.volume) %>%
    # Create a factor time variable for making boxplots
    group_by(mouse) %>%
    mutate(time.point = row_number(date)) %>%
    mutate(time.point = as.factor(time.point)) %>%
    dplyr::select(date, mouse, treatment.group, time.point, total.tumor.volume) %>%
    rename("tumor.volume" = "total.tumor.volume")
  
  return(meas)
}
```

```{r formatting}
meas <- format_rawtumor(raw.tumor)

head(meas)
```

```{r calculate tumor volume and set up groups-alternative eval=F}

# Calculate tumor volume and save in a new column : tumor.size
raw.tumor$tumor.volume <- (raw.tumor$`tumor.length.(mm)`*raw.tumor$`tumor.width.(mm)`*raw.tumor$`tumor.width.(mm)`)/2

# Merge rows for mouse with more than 1 tumors : addition
merge.tumor <- aggregate(tumor.volume ~ date + tail.number + microbiome.sample + treatment, FUN = sum, data=raw.tumor)
merge.tumor <- merge.tumor[order(as.Date(merge.tumor$date, format="%d/%m/%Y")),]

#set up four separate groups in one column and remove the previous columns
merge.tumor$Groups <- paste(merge.tumor$microbiome.sample, merge.tumor$treatment)
merge.tumor = subset(merge.tumor, select = -c(microbiome.sample, treatment) )


```


# 3. Visualize

```{r linefit}
meas %>%
  ggplot(aes(x = date, y = tumor.volume)) +
  geom_line(aes(color = treatment.group, group = mouse), alpha = 0.1) +
  stat_smooth(aes(color = treatment.group), method = "lm")
  # geom_point(aes(color = treatment.group))
```

```{r boxplots}
box.meas <- 
  meas %>%
  ggplot(aes(time.point, tumor.volume)) +
  geom_boxplot(aes(color = treatment.group)) +
  geom_line(aes(group = mouse, color = treatment.group), alpha = 0.2) +
  theme_bw()

box.meas

ggsave(plot = box.meas, 
       file = "../figures/AOT00041318_boxplot.png",
       device = "png", height = 6, width = 8)
# raw.tumor = data.frame(raw.tumor)
# ggplot(data = raw.tumor)
```

```{r summarize}
summ.meas <- 
  meas %>%
  group_by(treatment.group, date) %>%
  summarize(mean = mean(tumor.volume),
            sd = sd(tumor.volume), .groups= 'drop') %>%
  mutate(lwr = mean - sd,
         upr = mean + sd) %>%
  # A negative error bar doesn't make sense in this context, set to 0
  mutate(lwr = if_else(lwr < 0, 0, lwr))
```

```{r line plot with points and error bars}
#error bar version
err.meas <- 
  summ.meas %>%
  ggplot(aes(x = date, y = mean, color = treatment.group)) +
  geom_line()+
  geom_point()+
  geom_errorbar(aes(ymin = lwr, ymax = upr))

err.meas

ggsave(plot = err.meas,
       file = "../figures/volume.over.time.png")
```

#Tumor free mice percent visualize barplot

```{r Percent of tumor free mice visualization}
#x = group (4)
#y = %
#[[[ last time point only ]]]

# Keep last time point tumor volume only
lasttimepoint <- meas[-c(1:50), ]
# Set up 4 dataframe for the four groups
preigg <- lasttimepoint[-c(3:10),]
postigg <- lasttimepoint[-c(1:2, 5:10),]
prepd1 <- lasttimepoint[-c(1:4, 8:10),]
postpd1 <- lasttimepoint[-c(1:7),]

# Calculate % 0 per group
percentzero <- data.frame(pre.igg = sum(preigg$tumor.volume %in% 0)  / nrow(preigg), post.igg = sum(postigg$tumor.volume %in% 0)  / nrow(postigg), pre.pd1 = sum(prepd1$tumor.volume %in% 0)  / nrow(prepd1), post.pd1 = sum(postpd1$tumor.volume %in% 0)  / nrow(postpd1))
#transpose row and column, rename column, add new column for treatment groups names
percentzero <- t(percentzero)
colnames(percentzero)[1] <- "Percent.of.tumor.free.mice"
vec <- c("Pre.igG", "Post.igG", "Pre.PD1", "Post.PD1")
percentzero <- cbind(percentzero, new_col = vec)
colnames(percentzero)[2] <- "Treatment.groups"

#Visualize
perc.tf <- 
  ggplot(data = percentzero, aes(x = Treatment.groups, 
                                 y = Percent.of.tumor.free.mice, 
                                 fill = Treatment.groups)) + 
    geom_bar(stat = "identity")+
    ggtitle("Tumor Free Mice % at the Last Time Point per Treatment Groups")

ggsave(plot = perc.tf,
       file = "../figures/percenttumorfree.png")
```

#IgG vs PD1 per group per timepoint barplot

```{r igg vs PD1 per group visualization}
#2 groups (pre vs post DI)
#mean pd1 - mean igg
#y = difference in mean tumor volume
#x = intervention staus (2, preDI [V3], postDI [V4]

#Set up pre and post groups, remove unnecessary columns
pre.igg <- summ.meas[-c(7:24),]
pre.pd1 <- summ.meas[-c(1:6, 13:24),]
post.igg <- summ.meas[-c(1:12, 19:24),]
post.pd1 <- summ.meas[-c(1:18),]

pre.igg = subset(pre.igg, select = -c(date, sd, lwr, upr, treatment.group) )
post.igg = subset(post.igg, select = -c(date, sd, lwr, upr, treatment.group) )
pre.pd1 = subset(pre.pd1, select = -c(date, sd, lwr, upr, treatment.group) )
post.pd1 = subset(post.pd1, select = -c(date, sd, lwr, upr, treatment.group) )

# Calculate tumor volume differences between igg and pd1 and save in a new column : tumor.volume.differences, add back treatment.group
pre.iggvspd1 <- data.frame(tumor.volume.differences = (pre.pd1$mean - pre.igg$mean))
post.iggvspd1 <- data.frame(tumor.volume.differences = (post.pd1$mean - post.igg$mean))

#Merge mean tumor volume dif dataset as one, add 2 treatment.groups - pre and post-DI
treatments <- data.frame("treatment.groups" = c("Pre-DI.timepoint.1", "Pre-DI.timepoint.2", "Pre-DI.timepoint.3", "Pre-DI.timepoint.4", "Pre-DI.timepoint.5", "Pre-DI.timepoint.6", "Post-DI.timepoint.1", "Post-DI.timepoint.2", "Post-DI.timepoint.3", "Post-DI.timepoint.4", "Post-DI.timepoint.5", "Post-DI.timepoint.6"))
iggvspd1 <- cbind(t(pre.iggvspd1), t(post.iggvspd1))
iggvspd1 <- t(iggvspd1)
iggvspd1 <- cbind(iggvspd1, Treatment.groups = treatments$treatment.groups)

#Transform mean tumor differences to numeric value
iggvspd1 <- transform(iggvspd1, tumor.volume.differences = as.numeric(tumor.volume.differences))
# Create a factor time variable for making lineplot and barplot visualization
iggvspd1$timepoint <- c("1", "2", "3", "4", "5", "6","1", "2", "3", "4", "5", "6")
iggvspd1$treatment.group <- c("Pre-DI","Pre-DI","Pre-DI","Pre-DI","Pre-DI","Pre-DI", "Post-DI", "Post-DI","Post-DI","Post-DI","Post-DI","Post-DI")

```

```{r Visualization}
#Line graph
ggplot(data = iggvspd1, aes(x=timepoint, y=tumor.volume.differences, group = treatment.group, color = treatment.group)) + 
    geom_line()+
    geom_point()+
    ggtitle("Difference in mean tumor volume between IgG and anti-PD1 pre/post DI treatment")+
    theme(plot.title = element_text(size=12))

ggsave("../figures/iggvspd1fig.png")
```


```{r graveyard eval=F}
#Count % of 0
  sum(lasttimepoint$tumor.volume %in% 0)  / nrow(lasttimepoint)
#tumor free visualization
ggplot(data = percentzero, aes(x=Treatment.groups, y=Percent.of.tumor.free.mice, fill = Treatment.groups)) + 
    geom_bar(stat = "identity") +
    ggtitle("Tumor Free Mice % at the Last Time Point per Treatment Groups") 

ggsave("../figures/percenttumorfree.png")
```    

```{r}
#Bargraph for igg vs pd1 mean tumor diff
ggplot(data = iggvspd1, aes(x=timepoint, y=tumor.volume.differences, fill = treatment.group)) + 
    geom_bar(stat = "identity")+
    ggtitle("Difference in mean tumor volume between IgG and anti-PD1 pre/post DI treatment")+
    theme(plot.title = element_text(size=9))+
    theme(axis.text.x=element_text(angle=45, hjust = 1))+
    ggsave("../figures/iggvspd1fig.png")
```


# Grant figure

```{r}
meas.exp1 <- format_rawtumor(raw.tumor.exp1)

summ.meas.exp1 <- 
  meas.exp1 %>%
  group_by(treatment.group, date) %>%
  summarize(mean = mean(tumor.volume),
            sd = sd(tumor.volume), .groups= 'drop') %>%
  mutate(lwr = mean - sd,
         upr = mean + sd) %>%
  # A negative error bar doesn't make sense in this context, set to 0
  mutate(lwr = if_else(lwr < 0, 0, lwr)) %>%
  group_by(treatment.group) %>%
  arrange(date) %>%
  mutate(timepoint = row_number()) %>%
  ungroup() %>%
  mutate(treatment.status = ifelse(grepl("post", treatment.group), "Post DI", "Pre DI"),
         drug.intervention = ifelse(grepl("IgG", treatment.group), "igg", "antipd1"))

summ.meas.exp1
```

```{r}
summ.meas.exp1 %>%
  filter(timepoint == 6) %>%
  mutate(dif.means = )
```



```{r}
iggvspd1.grant <- summ.meas.exp1 %>%
  select(treatment.status, drug.intervention, timepoint, mean) %>%
  spread(key = "drug.intervention", value = "mean") %>%
  mutate(tumor.volume.difference = antipd1 - igg)

iggvspd1.grant
```

```{r}
ggplot(data = iggvspd1.grant, aes(x=timepoint, y=tumor.volume.difference, group = fct_relevel(treatment.status, "Pre DI", "Post DI"), 
                                  color = fct_relevel(treatment.status, "Pre DI", "Post DI"))) + 
  geom_line()+
  geom_point()+
  labs(x = "Timepoint", y = "Difference in Tumor Volume from IgG Control") +
  scale_color_manual(breaks = c("Pre DI", "Post DI"),
                     values = c("black", "darkred"),
                     labels = c("Pre-dietary intervention", "Post-dietary intervention"),
                     name = "Gavaged with Human\n     Stool Sample") +
  theme_bw() 
  # theme(plot.title = element_text(size=12))

ggsave("../figures/iggvspd1fig_grant.pdf", width = 6, height = 4)
```



# Remaking tumor volume vs time plot for mimic02

```{r mimic-02 data prep}

raw.tumor.exp2.filter <- 
  raw.tumor.exp2 %>%
  drop_na(microbiome.sample) %>%
  rename("treatment" = "cage (treatment)")

meas.exp2 <- format_rawtumor(raw.tumor.exp2.filter)

summ.meas.exp2 <-
  meas.exp2 %>%
  group_by(treatment.group, date) %>%
  summarize(mean = mean(tumor.volume),
            sd = sd(tumor.volume), .groups= 'drop') %>%
  mutate(lwr = mean - sd,
         upr = mean + sd) %>%
  # A negative error bar doesn't make sense in this context, set to 0
  mutate(lwr = if_else(lwr < 0, 0, lwr)) %>%
  group_by(treatment.group) %>%
  arrange(date) %>% 
  mutate(Timepoint = row_number()) %>%
  ungroup() %>%
   mutate(treatment.status = ifelse(grepl("Fitness", treatment.group), "Fitness", "Saline"),
         drug.intervention = ifelse(grepl("IgG", treatment.group), "igg", "antipd1")) %>%
  drop_na(sd)

summ.meas.exp2$Timepoint <- as.factor(summ.meas.exp2$Timepoint)
```

```{r mimic-02 line plot}

summ.meas.exp2 %>%
  ggplot(aes(x = Timepoint, y = mean, group = treatment.group, color = treatment.group)) +
  geom_line(position = position_dodge(width = .5))+
  geom_point(position = position_dodge(width = .5))+
  ylab("Mean Tumor Volume") +
  ggtitle("Tumor Volume vs. Time for Mimic-02") +
  theme_bw() +
  scale_color_brewer(palette = "Dark2") +
  geom_errorbar(aes(ymin = lwr, ymax = upr),
                width = 1,
                position = position_dodge(width = .5))

ggsave("../figures/tumorvolume-mimic02.png", width = 9, height = 5)

```

```{r mimic-01 plot}

summ.meas.exp1.group %>%
  ggplot(aes(x = Timepoint, y = mean, group = treatment.group, color = treatment.group)) +
  geom_line(position = position_dodge(width = .5))+
  geom_point(position = position_dodge(width = .5))+
  ylab("Mean Tumor Volume") +
  ggtitle("Tumor Volume vs. Time for Mimic-01") +
  theme_bw() +
  scale_color_brewer(palette = "Dark2") +
  geom_errorbar(aes(ymin = lwr, ymax = upr),
                width = 1,
                position = position_dodge(width = .5))

ggsave("../figures/tumorvolume-mimic01.png", width = 9, height = 5)



```





```{r Combined mimic plot data prep}

summ.meas.exp1.group <- unique(summ.meas.exp1$treatment.group) %>%
  str_replace("HONC-60-55.v3","pre-DI") %>%
  as.data.frame() %>% 
  rename("group" = ".") %>%
  mutate(treatment.group = unique(summ.meas.exp1$treatment.group)) %>%
  left_join(summ.meas.exp1) %>%
  arrange(date) %>%
  select(-treatment.group) %>%
  rename("treatment.group" = "group") %>% 
  rename("Timepoint" = "timepoint") 

summ.meas.exp1.group$Timepoint <- as.factor(summ.meas.exp1.group$Timepoint)

summ.meas.exp12 <- 
  summ.meas.exp1.group %>%
  bind_rows(summ.meas.exp2) %>%
  rename("Treatment Group" = "treatment.group")


```


```{r Combined mimic plot}
summ.meas.exp12 %>%
  ggplot(aes(x = Timepoint, y = mean, group = `Treatment Group`, color = `Treatment Group`)) +
  geom_line(position = position_dodge(width = .6))+
  geom_point(position = position_dodge(width = .6))+
  ylab("Mean Tumor Volume") +
  ggtitle("Tumor Volume vs. Time for Mimic-01 and 02") +
  theme_bw() + 
  scale_color_brewer(palette = "Dark2") +
  geom_errorbar(aes(ymin = lwr, ymax = upr),
                width = 1,
                position = position_dodge(width = .6)) 


ggsave("../figures/tumorvolume-mimic01and02.png", width = 9, height = 5)

```

# Version 2 with a few more generalizations

```{r}
# Read in all tumor size spreadsheets from the repo
files <- list.files("../data/tumor-size/", 
                    full.names = TRUE)
all.sizes <- lapply(files, readxl::read_xlsx)

# Rename the columns of all files (careful here)
changeAllNamesAndReformat <- function(df) {
    colnames(df) <- c("date", "tail.number", "treatment", "microbiome.sample",
                 "weight.g", "tumor.size.mm", "tumor.length.mm", 
                 "tumor.width.mm")
    df %>%
    mutate_at(vars(-("date")), as.character)
}

all.sizes.named <- lapply(all.sizes, changeAllNamesAndReformat)

# Extra hack to clean up a date col
all.sizes.named[[4]] <- 
  all.sizes.named[[4]] %>%
  mutate(date = as.POSIXct(strptime(date, "%m/%d/%y")))

# Files must be harmonized first
df <- bind_rows(all.sizes.named)

head(df)
```

```{r}
df %>%
  select(-tumor.size.mm) %>%
  mutate(cage = NA)

```

