---
title: "processing_R-formatted-data"
author: "Rebecca Hoyd"
date: "1/24/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readxl)
library(tidyverse)

# source("00-paths.R")
```


# Load data 

```{r}
#tsize.files <- list.files(file.path(paths$box, 'data'), pattern = "AOT", full.names = T)
#tsize.files <- c(tsize.files[3:10], tsize.files[1])
#tsize.file.2 <- unlist(lapply(tsize.files, function(x) list.files(x, pattern = "_size")))

#tsize.raw <- lapply(1:9, function(x) read_excel(file.path(tsize.files[x], tsize.file.2[x])))

#inject.dates <- read_excel(file.path(paths$box, "data", "mimic_injection_dates.xlsx"))

```

Read in all tumor size measurements
 
```{r AP Data Read Test Code}
tsize.files <- list.files("../data/tumor-size", 
                          pattern = "AOT", 
                          full.names = TRUE,
                          recursive = TRUE)

tsize.files
```
Filter any conflicting copy files, which have an appended computer ID starting with "CANCER".

```{r}
tsize.files <- 
  tsize.files[!grepl("-CANCER-", tsize.files)]

tsize.files
```
Read in files to list

```{r}

tsize.raw <- lapply(tsize.files, read_xlsx)
names(tsize.raw) <- tsize.files
```


Read in a separate table of the injection dates for each experiment, to be used as the zero time point. 

```{r}
# tsize.files <- c(tsize.files[3:10], tsize.files[1])
# tsize.file.2 <- unlist(lapply(tsize.files, function(x) list.files(x, pattern = "_size")))
# 
# tsize.raw <- lapply(1:13, function(x) read_excel(file.path(tsize.files[x], tsize.file.2[x])))

inject.dates <- read_xlsx("../data/mimic_injection_dates.xlsx")

```

# Functions

```{r}
calcTumorVol <- function(tmp, idate){
  tmp %>%
    mutate(tail.number = as.character(tail.number)) %>%
    mutate(tumor.length.mm = as.numeric(`tumor.length.(mm)`),
           tumor.width.mm = as.numeric(`tumor.width.(mm)`)) %>%
    mutate(tumor.volume = (tumor.length.mm * (tumor.width.mm^2)) / 2,
           tumor.volume = dplyr::if_else(is.na(tumor.volume),
                                         true = 0,
                                         false = tumor.volume)) %>%
    group_by(tail.number, treatment.group, date) %>%
    summarise(tumor.volume = sum(tumor.volume)) %>%
    ungroup() %>%
    mutate(days.from.injection = as.numeric(as.Date(date) - as.Date(idate)))  %>%
    select(-date)
}
```

# Experiment specific formatting

```{r}
zero.vals <- c("n/a", "N/A")

mim1 <- tsize.raw[[1]] %>%
  mutate(`tumor.length.(mm)` = ifelse(is.na(`tumor.length.(mm)`), 
                                      0, 
                                      `tumor.length.(mm)`),
          `tumor.width.(mm)` = ifelse(is.na(`tumor.width.(mm)`), 
                                      0, `tumor.width.(mm)`)) %>%
  mutate(
    # condition = dplyr::if_else(grepl("v3", microbiome.sample),
    #                                true = "mimic1.pre-DI",
    #                                false = "mimic1.post-DI"),
         treatment.group = paste(treatment, microbiome.sample, sep = " x ")) %>%
  calcTumorVol(., inject.dates$`Date of Injection`[1]) %>%
  separate(treatment.group, into = c("treatment", "microbiome.sample"), sep = " x ") %>%
  mutate(unique.mouse.id = paste(tail.number, treatment, microbiome.sample, sep = "_"),
         experiment = "mimic1") %>% 
  mutate(treatment = ifelse(treatment %in% c("Anti-PD-1"), "Anti-PD1", "IgG"),
         microbiome.sample = ifelse(microbiome.sample %in% c("HONC-60-55.v3"), "HONC60-55 v3", "HONC60-55 v4"))

mim2 <- tsize.raw[[2]] %>%
  drop_na(`tumor.length.(mm)`) %>%
  mutate(`tumor.length.(mm)` = as.numeric(`tumor.length.(mm)`),
         `tumor.width.(mm)` = as.numeric(`tumor.width.(mm)`),
         treatment.group = paste(gsub(".-(.*)", "\\1", `cage (treatment)`),
                                 microbiome.sample, sep = " x ")) %>%
  calcTumorVol(., inject.dates$`Date of Injection`[2]) %>%
  separate(treatment.group, into = c("treatment", "microbiome.sample"), sep = " x ") %>%
  mutate(unique.mouse.id = paste(tail.number, treatment, microbiome.sample, sep = "_"),
         experiment = "mimic2")

# Problem: need to split mouse ids by cage
mim3 <- tsize.raw[[3]] %>%
  filter(`on treatment?` == "Yes" & `tumor.length.(mm)` != "n/a") %>% 
  mutate(`tumor.length.(mm)` =ifelse(`tumor.length.(mm)` %in% zero.vals, 0, `tumor.length.(mm)`),
         `tumor.width.(mm)` = ifelse(`tumor.width.(mm)` %in% zero.vals, 0, `tumor.width.(mm)`)) %>%
  mutate(`tumor.length.(mm)` = as.numeric(`tumor.length.(mm)`),
         `tumor.width.(mm)` = as.numeric(`tumor.width.(mm)`),
         condition =  "Fitness:DL017",
         treatment = ifelse(cage %in% c(1,2), "IgG", "PD1"),
         treatment.group = paste(treatment, condition, sep = " x ")) %>%
  mutate(tail.number = paste(tail.number, cage, sep = " x ")) %>%
  calcTumorVol(., inject.dates$`Date of Injection`[3]) %>%
  separate(treatment.group, into = c("treatment", "microbiome.sample"), sep = " x ") %>%
  mutate(unique.mouse.id = paste(tail.number, treatment, microbiome.sample, sep = "_"),
         experiment = "mimic3") %>%
  separate(tail.number, into = c("tail.number", "cage"), sep = " x ")



mim5 <- tsize.raw[[5]] %>%
  drop_na(`tumor.length.(mm)`) %>%
    filter(`tumor.length.(mm)` != "n/a") %>%
  mutate(`tumor.length.(mm)` = as.numeric(`tumor.length.(mm)`),
         `tumor.width.(mm)` = as.numeric(`tumor.width.(mm)`),
         treatment = ifelse(cage %in% c(1,4), "IgG", "PD1"),
         microbiome.sample = ifelse(cage %in% c(1,2), "102v3", "102v4"),
         treatment.group = paste(treatment,microbiome.sample, sep = " x "),
         tail.number = paste(tail.number, cage, sep = " x ")) %>%
  calcTumorVol(., inject.dates$`Date of Injection`[5]) %>%
  separate(treatment.group, into = c("treatment", "microbiome.sample"), sep = " x ") %>%
  mutate(unique.mouse.id = paste(tail.number, treatment, microbiome.sample, sep = "_"),
         experiment = "mimic5") %>%
  separate(tail.number, into = c("tail.number", "cage"), sep = " x ")

mim6 <- tsize.raw[[6]] %>%
  drop_na(`tumor.length.(mm)`) %>%
    filter(`tumor.length.(mm)` != "n/a") %>%
  mutate(`tumor.length.(mm)` = as.numeric(`tumor.length.(mm)`),
         `tumor.width.(mm)` = as.numeric(`tumor.width.(mm)`),
         treatment.group = paste(Treatment,microbiome.sample, sep = " x "),
         tail.number = paste(tail.number, cage, sep = " x "),
         date = as.POSIXct(str_replace(as.character(date), "2021", "2022"))) %>%
  calcTumorVol(., inject.dates$`Date of Injection`[6]) %>%
  separate(treatment.group, into = c("treatment", "microbiome.sample"), sep = " x ") %>%
  mutate(unique.mouse.id = paste(tail.number, treatment, microbiome.sample, sep = "_"),
         experiment = "mimic6") %>%
  separate(tail.number, into = c("tail.number", "cage"), sep = " x ")

mim7 <- tsize.raw[[7]] %>%
  drop_na(`tumor.length.(mm)`) %>%
    filter(`tumor.length.(mm)` != "n/a") %>%
  mutate(`tumor.length.(mm)` = as.numeric(`tumor.length.(mm)`),
         `tumor.width.(mm)` = as.numeric(`tumor.width.(mm)`),
         Treatment = ifelse(cage %in% c(1,2), "Anti-PD1", "IgG"),
         treatment.group = paste(Treatment,microbiome.sample, sep = " x "),
         tail.number = paste(tail.number, cage, sep = " x ")) %>%
  calcTumorVol(.,inject.dates$`Date of Injection`[7]) %>%
  separate(treatment.group, into = c("treatment", "microbiome.sample"), sep = " x ") %>%
  mutate(unique.mouse.id = paste(tail.number, treatment, microbiome.sample, sep = "_"),
         experiment = "mimic7") %>%
  separate(tail.number, into = c("tail.number", "cage"), sep = " x ")

mim8 <- tsize.raw[[8]] %>%
  drop_na(`tumor.length.(mm)`) %>%
    filter(`tumor.length.(mm)` != "n/a") %>%
  mutate(`tumor.length.(mm)` = as.numeric(`tumor.length.(mm)`),
         `tumor.width.(mm)` = as.numeric(`tumor.width.(mm)`),
         Treatment = ifelse(cage %in% c(1,2), "Anti-PD1", "IgG"),
         microbiome.sample = "DL017",
         treatment.group = paste(Treatment,microbiome.sample, sep = " x "),
         tail.number = paste(tail.number, cage, sep = " x ")) %>%
  calcTumorVol(.,inject.dates$`Date of Injection`[8]) %>%
  separate(treatment.group, into = c("treatment", "microbiome.sample"), sep = " x ") %>%
  mutate(unique.mouse.id = paste(tail.number, treatment, microbiome.sample, sep = "_"),
         experiment = "mimic8") %>%
  separate(tail.number, into = c("tail.number", "cage"), sep = " x ")
```


```{r}
# I don't see mimic 9 in the input file -- skipping for now
mim9 <- tsize.raw[[9]] %>%
  drop_na(microbiome.sample) %>%
  filter(!grepl("n/a", microbiome.sample)) %>%
  mutate(Treatment = ifelse(cage %in% c(1,3), "Anti-PD1", "IgG"),
         microbiome.sample = gsub("V", "v", microbiome.sample),
         treatment.group = paste(Treatment,microbiome.sample, sep = " x "),
         tail.number = paste(tail.number, cage, sep = " x ")) %>%
  calcTumorVol(., as.POSIXct("2022-04-11")) %>%
  separate(treatment.group, into = c("treatment", "microbiome.sample"), sep = " x ") %>%
  mutate(unique.mouse.id = paste(tail.number, treatment, microbiome.sample, sep = "_"),
         experiment = "mimic9") %>%
  separate(tail.number, into = c("tail.number", "cage"), sep = " x ")

```

```{r mimic 4, saved separately because it got complicated}
mim4.baddate <- tsize.raw[[4]] %>%
  drop_na(`tumor.length.(mm)`) %>%
    filter(`tumor.length.(mm)` != "n/a") %>%
  mutate(`tumor.length.(mm)` = as.numeric(`tumor.length.(mm)`),
         `tumor.width.(mm)` = as.numeric(`tumor.width.(mm)`),
         treatment = ifelse(cage %in% c(3,4), "IgG", "PD1"),
         microbiome.sample = ifelse(cage %in% c(1,2), "84v3", "84v4"),
         treatment.group = paste(treatment,microbiome.sample, sep = " x "),
         tail.number = paste(tail.number, cage, sep = " x ")
         )

mim4.good <- mim4.baddate %>%
  filter(grepl("/", date)) %>%
  mutate(date = paste0("2021-10-", gsub(".*/(.*)/.*", "\\1", date)))
mim4.fixdate <- mim4.baddate %>%
  filter(!grepl("/", date)) %>%
  mutate(date = as.numeric(date)) %>%
  mutate(date = as.character(as.Date(date, origin = "1899-12-30"))) %>%
  bind_rows(mim4.good)
  
mim4 <- mim4.fixdate %>% 
  calcTumorVol(., inject.dates$`Date of Injection`[4]) %>%
  separate(treatment.group, into = c("treatment", "microbiome.sample"), sep = " x ") %>%
  mutate(unique.mouse.id = paste(tail.number, treatment, microbiome.sample, sep = "_"),
         experiment = "mimic4") %>%
  separate(tail.number, into = c("tail.number", "cage"), sep = " x ")

```

```{r AP mimic cleanup}
mim10 <- tsize.raw[[grep("mimic10", names(tsize.raw))]] %>%
  drop_na(`tumor.number`) %>%
  mutate(`tumor.length.(mm)` = as.numeric(`tumor.length.(mm)`),
         `tumor.width.(mm)` = as.numeric(`tumor.width.(mm)`),
         `date` = as.character(`date`),
         Treatment = ifelse(cage %in% c(1,2), "Anti-PD1","IgG"),
         microbiome.sample = ifelse(cage %in% c(1,3), "HONC-60 68v1", "HONC-60 68v2"),
         treatment.group = paste(Treatment, microbiome.sample, sep = " x "),
         tail.number = paste(tail.number, cage, sep = " x ")) %>%
  calcTumorVol(., as.POSIXct("2022-05-12")) %>%
  separate(treatment.group, into = c("treatment", "microbiome.sample"), sep = " x ") %>%
  mutate(unique.mouse.id = paste(tail.number, treatment, microbiome.sample, sep = "_"),
         experiment = "mimic10") %>%
  separate(tail.number, into = c("tail.number", "cage"), sep = " x ") %>%
# mouse 3 cage 4 died and has incomplete dataset
  filter(unique.mouse.id != "3 x 4_IgG_HONC-60 68v2")

mim11 <- tsize.raw[[grep("mimic11", names(tsize.raw))]] %>%
  drop_na(tumor.number) %>%
  mutate(`tumor.length.(mm)` = as.numeric(`tumor.length.(mm)`),
         `tumor.width.(mm)` = as.numeric(`tumor.width.(mm)`),
         `date` = as.character(`date`),
         Treatment = ifelse(cage %in% c(1,2), "Anti-PD1","IgG"), 
         treatment.group = paste(Treatment, microbiome.sample, sep = " x "),
         tail.number = paste(tail.number, cage, sep = " x ")) %>% 
  calcTumorVol(., as.POSIXct("2022-06-23")) %>%
  separate(treatment.group, into = c("treatment", "microbiome.sample"), sep = " x ") %>%
  mutate(unique.mouse.id = paste(tail.number, treatment, microbiome.sample, sep = "_"),
         experiment = "mimic11") %>%
  separate(tail.number, into = c("tail.number", "cage"), sep = " x ") 

mim12 <- tsize.raw[[grep("mimic12", names(tsize.raw))]] %>%
   drop_na(tumor.number) %>%
  mutate(`tumor.length.(mm)` = as.numeric(`tumor.length.(mm)`),
         `tumor.width.(mm)` = as.numeric(`tumor.width.(mm)`),
         `date` = as.character(`date`),
         Treatment = ifelse(cage %in% c(1,2), "Anti-PD1","IgG"),
         microbiome.sample = ifelse(cage %in% c(1,3), "HONC60-85 v2", "HONC60-85 v1"),
         treatment.group = paste(Treatment, microbiome.sample, sep = " x "),
         tail.number = paste(tail.number, cage, sep = " x ")) %>%
  calcTumorVol(., as.POSIXct("2022-06-30")) %>%
  separate(treatment.group, into = c("treatment", "microbiome.sample"), sep = " x ") %>%
  mutate(unique.mouse.id = paste(tail.number, treatment, microbiome.sample, sep = "_"),
         experiment = "mimic12") %>%
  separate(tail.number, into = c("tail.number", "cage"), sep = " x ")

mim13 <- tsize.raw[[grep("mimic13", names(tsize.raw))]] %>%
  drop_na(tumor.number) %>%
  mutate(`tumor.length.(mm)` = as.numeric(`tumor.length.(mm)`),
         `tumor.width.(mm)` = as.numeric(`tumor.width.(mm)`),
         `date` = as.character(`date`),
         Treatment = ifelse(cage %in% c(1,4), "Anti-PD1","IgG"),
         microbiome.sample = ifelse(cage %in% c(1,2), "HONC60-84 v3", "HONC60-84 v4"),
         treatment.group = paste(Treatment, microbiome.sample, sep = " x "),
         tail.number = paste(tail.number, cage, sep = " x ")) %>%
  calcTumorVol(., as.POSIXct("2022-07-07")) %>%
  separate(treatment.group, into = c("treatment", "microbiome.sample"), sep = " x ") %>%
  mutate(unique.mouse.id = paste(tail.number, treatment, microbiome.sample, sep = "_"),
         experiment = "mimic13") %>%
  separate(tail.number, into = c("tail.number", "cage"), sep = " x ") %>%
  mutate(treatment = ifelse(grepl("3 x 3", unique.mouse.id), "Anti-PD1", treatment))

mim16 <- tsize.raw[[grep("mimic16", names(tsize.raw))]] %>%
  drop_na(`tumor.width.(mm)`) %>%
   mutate(`tumor.length.(mm)` = as.numeric(`tumor.length.(mm)`),
         `tumor.width.(mm)` = as.numeric(`tumor.width.(mm)`),
         `date` = as.character(`date`),
         Treatment = ifelse(cage %in% c(1,2), "Anti-PD1","IgG"),
         microbiome.sample = ifelse(cage %in% c(1,3), "HONC60-85v1 + Blautia", "HONC60-85v1"),
         treatment.group = paste(Treatment, microbiome.sample, sep = " x "),
         tail.number = paste(tail.number, cage, sep = " x "))  %>%
  calcTumorVol(., as.POSIXct("2023-02-01")) %>%
  separate(treatment.group, into = c("treatment", "microbiome.sample"), sep = " x ") %>%
  mutate(unique.mouse.id = paste(tail.number, treatment, microbiome.sample, sep = "_"),
         experiment = "mimic16") %>%
  separate(tail.number, into = c("tail.number", "cage"), sep = " x ")


mim17 <- tsize.raw[[grep("mimic17", names(tsize.raw))]] %>%
  drop_na(tumor.number) %>%
  mutate(`tumor.length.(mm)` = as.numeric(`tumor.length.(mm)`),
         `tumor.width.(mm)` = as.numeric(`tumor.width.(mm)`),
         `date` = as.character(`date`),
         Treatment = ifelse(cage %in% c(2,3), "Anti-PD1","IgG"),
         microbiome.sample = ifelse(cage %in% c(2,4), "HONC60-85v1 + Blautia", "HONC60-85v1"),
         treatment.group = paste(Treatment, microbiome.sample, sep = " x "),
         tail.number = paste(tail.number, cage, sep = " x ")) %>%
  calcTumorVol(., as.POSIXct("2023-03-30")) %>%
  separate(treatment.group, into = c("treatment", "microbiome.sample"), sep = " x ") %>%
  mutate(unique.mouse.id = paste(tail.number, treatment, microbiome.sample, sep = "_"),
         experiment = "mimic17") %>%
  separate(tail.number, into = c("tail.number", "cage"), sep = " x ")
```


```{r}

mim18 <- tsize.raw[[grep("mimic18", names(tsize.raw))]] %>%
  drop_na(tumor.number) %>%
  mutate(`tumor.length.(mm)` = as.numeric(`tumor.length.(mm)`),
         `tumor.width.(mm)` = as.numeric(`tumor.width.(mm)`),
         `date` = as.character(`date`),
         Treatment = ifelse(cage %in% c(3,4,7,8), "Anti-PD1","IgG"),
         microbiome.sample = ifelse(cage %in% c(1,3,5,7), "HONC60-85v1 + Blautia", "HONC60-85v1"),
         tail.number = paste(tail.number, cage, sep = " x "),
         Treatment = ifelse(grepl("4 x 1|4 x 2|4 x 5|4 x 6",tail.number), "Anti-PD1", Treatment),
         microbiome.sample = ifelse(grepl("4 x 2",tail.number),"HONC60-85v1 + Blautia",microbiome.sample),
         microbiome.sample = ifelse(grepl("4 x 5",tail.number),"HONC60-85v1",microbiome.sample),
         tail.number = ifelse(grepl("4 x 1",tail.number),"1 x 7", tail.number),
         tail.number = ifelse(grepl("4 x 2",tail.number),"2 x 7", tail.number),
         tail.number = ifelse(grepl("3 x 4",tail.number),"1 x 8", tail.number),
         tail.number = ifelse(grepl("4 x 5",tail.number),"2 x 8", tail.number),
         tail.number = ifelse(grepl("4 x 6",tail.number),"3 x 8", tail.number),
         cage = ifelse(grepl("1 x 7|2 x 7", tail.number),7,cage),
         cage = ifelse(grepl("1 x 8|2 x 8|3 x 8", tail.number),8,cage),
         treatment.group = paste(Treatment, microbiome.sample, sep = " x ")) %>%
  filter(tail.number != "1 x 3") %>%
  filter(tail.number != "2 x 3") %>%
  calcTumorVol(., as.POSIXct("2023-06-22")) %>%
  separate(treatment.group, into = c("treatment", "microbiome.sample"), sep = " x ") %>%
  mutate(unique.mouse.id = paste(tail.number, treatment, microbiome.sample, sep = "_"),
         experiment = "mimic18") %>%
  separate(tail.number, into = c("tail.number", "cage"), sep = " x ")

```

```{r}
# mim16 <- 
#  tsize.raw[[grep("mimic16", names(tsize.raw))]] %>%
#   drop_na(microbiome.sample) %>%
#   filter(!grepl("na", `tumor.width.(mm)`)) %>% 
#   calcTumorVol(., as.POSIXct("2023-02-01")) 
  

# 
#   mutate(Treatment = ifelse(cage %in% c(1,2), "Anti-PD1","IgG"),
#          treatment.group = paste(Treatment, microbiome.sample, sep = " x "),
#          tail.number = paste(tail.number, cage, sep = " x ")) %>% 
```



# Combine results

```{r}
mimic.cleaned <- mim1 %>%
  bind_rows(mim2) %>%
  bind_rows(mim3) %>%
  bind_rows(mim4) %>%
  bind_rows(mim5) %>%
  bind_rows(mim6) %>%
  bind_rows(mim7) %>%
  bind_rows(mim8) %>%
  # bind_rows(mim9) %>% # mimic9 is missing from the input files
  bind_rows(mim10) %>%
  bind_rows(mim11) %>%
  bind_rows(mim12) %>%
  bind_rows(mim13) %>%
  bind_rows(mim16) %>%
  bind_rows(mim17) %>%
  bind_rows(mim18)
```

# Save

```{r}
write.csv(x = mimic.cleaned, 
          file = paste0("../data/", 
                        format(Sys.Date(), "%F"),
                        "_tumor-size_R-formatted.csv"),
          row.names = F)
```