---
title: "Mimic.tumor.vs.time"
author: "Yangyang Liu"
date: "6/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load required packages
library(readxl)
library(tidyverse)

```

# Load data 

```{r}
tsizes <- read.csv("../data/2022-03-22_tumor-size_R-formatted.csv", stringsAsFactors = F)
```



# Clean, format and create variables - Only from 1st run!

```{r functions}
# calcTumorVol <- function(tmp){
#   tmp %>%
#     mutate(tail.number = as.character(tail.number)) %>%
#     mutate(tumor.volume = (`tumor.length.(mm)` * (`tumor.width.(mm)`^2)) / 2,
#            tumor.volume = dplyr::if_else(is.na(tumor.volume),
#                                          true = 0,
#                                          false = tumor.volume)) %>%
#     group_by(tail.number, treatment.group, date) %>%
#     summarise(tumor.volume = sum(tumor.volume)) %>%
#     ungroup() %>%
#     mutate(time.point = as.numeric(as.factor((date))))  %>%
#     select(-date)
# }
```

```{r}
# zero.vals <- c("n/a", "N/A")
# 
# mim1 <- tsize.raw[[1]] %>%
#   mutate(`tumor.length.(mm)` = ifelse(is.na(`tumor.length.(mm)`), 0, `tumor.length.(mm)`),
#           `tumor.width.(mm)` = ifelse(is.na(`tumor.width.(mm)`), 0, `tumor.width.(mm)`)) %>%
#   mutate(condition = dplyr::if_else(grepl("v3", microbiome.sample),
#                                    true = "mimic1.pre-DI",
#                                    false = "mimic1.post-DI"),
#          treatment.group = paste(treatment, condition, sep = " x ")) %>%
#   calcTumorVol()
# 
# mim2 <- tsize.raw[[2]] %>%
#   drop_na(`tumor.length.(mm)`) %>%
#   mutate(`tumor.length.(mm)` =ifelse(`tumor.length.(mm)` %in% zero.vals, 0, `tumor.length.(mm)`),
#          `tumor.width.(mm)` = ifelse(`tumor.width.(mm)` %in% zero.vals, 0, `tumor.width.(mm)`)) %>%
#   mutate(`tumor.length.(mm)` = as.numeric(`tumor.length.(mm)`),
#          `tumor.width.(mm)` = as.numeric(`tumor.width.(mm)`),
#          treatment.group = paste(gsub(".-(.*)", "\\1", `cage (treatment)`),
#                                  microbiome.sample, sep = " x ")) %>%
#   calcTumorVol()
# 
# # Problem: need to split mouse ids by cage
# mim3 <- tsize.raw[[3]] %>%
#   drop_na(`tumor.length.(mm)`) %>%
#   filter(`tumor.length.(mm)` != "not present") %>%
#   mutate(`tumor.length.(mm)` =ifelse(`tumor.length.(mm)` %in% zero.vals, 0, `tumor.length.(mm)`),
#          `tumor.width.(mm)` = ifelse(`tumor.width.(mm)` %in% zero.vals, 0, `tumor.width.(mm)`)) %>%
#   mutate(`tumor.length.(mm)` = as.numeric(`tumor.length.(mm)`),
#          `tumor.width.(mm)` = as.numeric(`tumor.width.(mm)`),
#          condition =  "Fitness:DL017",
#          treatment = ifelse(grepl("1$", `cage (treatment)`), "IgG",
#                             ifelse(grepl("2$", `cage (treatment)`), "IgG", "PD1")),
#          treatment.group = paste(treatment, condition, sep = " x ")) %>%
#   mutate(tail.number = paste0(tail.number, `cage (treatment)`)) %>%
#   calcTumorVol()
# 
# mim4 <- tsize.raw[[4]] %>%
#   drop_na(`tumor.length.(mm)`) %>%
#   mutate(`tumor.length.(mm)` =ifelse(`tumor.length.(mm)` %in% zero.vals, 0, `tumor.length.(mm)`),
#          `tumor.width.(mm)` = ifelse(`tumor.width.(mm)` %in% zero.vals, 0, `tumor.width.(mm)`)) %>%
#   mutate(`tumor.length.(mm)` = as.numeric(`tumor.length.(mm)`),
#          `tumor.width.(mm)` = as.numeric(`tumor.width.(mm)`),
#          treatment.group = paste(microbiome.sample, Treatment, sep = "/"),
#          tail.number = paste(tail.number, cage)) %>%
#   calcTumorVol()

```

```{r}
mean.vals <- tsizes %>%
  mutate(treatment.group = paste(experiment, treatment, microbiome.sample, sep = " x ")) %>%
  group_by(treatment.group, days.from.injection) %>%
  summarise(mean.volume = mean(tumor.volume),
            sd.volume = sd(tumor.volume)) %>%
  ungroup() %>%
  mutate(lwr = mean.volume - sd.volume,
         upr = mean.volume + sd.volume) %>%
  mutate(lwr = if_else(lwr < 0, 0, lwr))
```


# tumor v time - save to make shiny function

```{r mimic-02 line plot}


mean.vals %>%
  ggplot(aes(x = days.from.injection, y = mean.volume, 
             group = treatment.group, color = treatment.group)) +
  geom_line()+
  geom_point()+
  labs(title = "Tumor Volume vs. Time for Mimic", x = "Time point", y = "Mean tumor volume") +
  theme_bw() +
  # scale_color_brewer(palette = "Dark2") 
  geom_errorbar(aes(ymin = lwr, ymax = upr),
                width = 1)


write.csv(mean.vals, "../shiny-apps/tumor-line-plots/2022-03-22_mean-tumor-volumes.csv", row.names = F)
```




