---
title: "tumor-size-pvalues"
author: "Dan Spakowicz"
date: "1/13/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load required packages
library(readxl)
library(tidyverse)

# Load file paths
source("00-paths.R")
```

# 1. Read in data 


```{r}
x <- read.csv("../data/2022-02-15_tumor-size_R-formatted.csv")
```

# Format

```{r}
y <- x %>%
  mutate(m.samp = gsub("-", "", gsub("\\.", "", gsub(" ", "", microbiome.sample))),
         ab = if_else(grepl("igg", 
                            treatment, 
                            ignore.case = TRUE),
                      true = "IgG",
                      false = "PD1")) %>%
  group_by(ab, m.samp, time.point, experiment) %>%
  summarise(mean.volume = mean(tumor.volume),
            sd.volume = sqrt(var(tumor.volume))) %>%
  ungroup()
```

```{r import data}
# x <- read_csv(file = "../shiny-apps/tumor-line-plots/mean-tumor-volumes.csv")
# 
# x %>%
#   head
```

```{r}
last <- 
  y %>%
  group_by(ab, m.samp, experiment) %>%
  filter(time.point == max(time.point))
  # filter(time.point == 6)

last %>%
  head
```

```{r}
re.label <- last %>%
  mutate(gavage = if_else(grepl("DL081", m.samp),
                          true = "FITNESS.DL081",
                          false = 
                  if_else(grepl("DL017", m.samp),
                                true = "FITNESS.DL017",
                                false = 
                  if_else(grepl("84v3", m.samp),
                          true = "BEWELL.84.rDI",
                          false = 
                  if_else(grepl("84v4", m.samp),
                          true = "BEWELL.84.tDI",
                          false = 
                  if_else(grepl("55v3", m.samp),
                          true = "BEWELL.55.rDI",
                          false = ,
                  if_else(grepl("55v4", m.samp),
                          true = "BEWELL.55.tDI",
                          false = "Saline"
                          )))))))

re.label %>%
  select(m.samp, ab, gavage, experiment)
```

```{r}
change.df <- 
  re.label %>%
  ungroup() %>%
  select(ab, gavage, mean.volume, sd.volume, experiment) %>%
  gather(-gavage, -ab, -experiment, key = "measurement", 
         value = "mm3") %>%
  filter(gavage != "Saline") %>%
  mutate(measurement.ab = paste(ab, measurement, sep = "_")) %>%
  select(-measurement, -ab) %>%
  spread(key = measurement.ab, value = mm3)

change.df
```

```{r}
split.change.df <- change.df%>%
  mutate(diff.mean.vol = IgG_mean.volume - PD1_mean.volume,
         diff.pooled.sd = sqrt(IgG_sd.volume^2 + PD1_sd.volume^2)
  ) %>%
  select(experiment, gavage, diff.mean.vol, diff.pooled.sd) %>%
  filter(grepl("55", gavage)) %>%
  mutate(groupn = case_when(experiment == "mimic1" & grepl("rDI", gavage)~2,
                            experiment == "mimic1" & grepl("tDI", gavage)~3,
                            experiment == "mimic6" & grepl("rDI", gavage)~2,
                            experiment == "mimic6" & grepl("tDI", gavage)~2))

pooled.change.df <- split.change.df %>%
  mutate(tx = diff.mean.vol*groupn,
         tsd = (diff.pooled.sd^2)*(groupn-1) + (tx^2)/groupn) %>%
  group_by(gavage) %>%
  summarise(tn = sum(groupn),
            tx = sum(tx),
            txx = sum(tsd)) %>%
  mutate(comb.mean = tx/tn,
         comb.sd = sqrt((txx-((tx^2)/tn))/(tn-1)))
```

```{r}
#https://stats.stackexchange.com/questions/30394/how-to-perform-two-sample-t-tests-in-r-by-inputting-sample-statistics-rather-tha
# m1, m2: the sample means
# s1, s2: the sample standard deviations
# n1, n2: the same sizes
# m0: the null value for the difference in means to be tested for. Default is 0. 
# equal.variance: whether or not to assume equal variance. Default is FALSE. 
t.test2 <- function(m1,m2,s1,s2,n1,n2,m0=0,equal.variance=FALSE)
{
    if( equal.variance==FALSE ) 
    {
        se <- sqrt( (s1^2/n1) + (s2^2/n2) )
        # welch-satterthwaite df
        df <- ( (s1^2/n1 + s2^2/n2)^2 )/( (s1^2/n1)^2/(n1-1) + (s2^2/n2)^2/(n2-1) )
    } else
    {
        # pooled standard deviation, scaled by the sample sizes
        se <- sqrt( (1/n1 + 1/n2) * ((n1-1)*s1^2 + (n2-1)*s2^2)/(n1+n2-2) ) 
        df <- n1+n2-2
    }      
    t <- (m1-m2-m0)/se 
    dat <- c(m1-m2, se, t, 2*pt(-abs(t),df))    
    names(dat) <- c("Difference of means", "Std Error", "t", "p-value")
    return(dat) 
}
```

```{r}
pooled.change.df
```

```{r}
# BEWELL.55
t.test2(m1 = 478.3746,
        m2 = 990.2632,
        s1 = 298.2834,
        s2 = 529.2055,
        n1 = 4,
        n2 = 5)
```

